server:
  port: 8090
spring:
  application:
    name: sba-gateway-service
  security:
    user:
      roles: SUPERUSER
      name: admin
      password: admin
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    user-service: /users/**
    search-service: /search/**
    technology-service: /technology/**
    training-service: /trainings/**
    payment-service: /payments/**